wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.7
    t:
      1:
      - 3
      4: 3.8.7
      5: 0.10.22
      8:
      - 3
      - 5
name:
  desc: null
  value: Sat Mar 20 01:39:01 2021
